global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'eureka-server'
    static_configs:
      - targets: ['eureka-server:8761']

  - job_name: 'feign-client'
    static_configs:
      - targets: ['feign-client:8079']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9095']
